'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const manheim=require('../painel/manheim');const {extractCode,locationState,publicResponse,publicVehicle,randomCode}=require('../vitrine-domain');
const root=path.join(__dirname,'..');const read=(file)=>fs.readFileSync(path.join(root,file),'utf8');
test('real Manheim timestamps, Simulcast preference, units and state are normalized',()=>{
 const csv='Inventory,Vin,Year,Make,Model,Odometer Value,Pickup Location,Starts At,Ends At,Condition Report Grade,Buy Now Price\nTimed Sale,1A,2020,Honda,Civic,20,FL - Miami,2026-09-29T14:00:00Z,2026-09-30T14:00:00Z,0.0,9000\nSimulcast,1A,2020,Honda,Civic,20,FL - Miami,2026-09-29T13:30:00Z,2026-09-29T14:00:00Z,0.0,';
 const parsed=manheim.parseCsv(csv),rows=manheim.chooseAuctionRows(manheim.normalizeRows(parsed,manheim.mapHeaders(parsed.headers)));
 assert.equal(rows.length,1);assert.equal(rows[0].startsAt,'2026-09-29T13:30:00Z');assert.equal(rows[0].conditionGrade,'0.0');assert.equal(rows[0].miles,20);assert.equal(locationState(rows[0].location),'Florida');assert.equal(rows[0].hasBuyNow,true);
});
test('short code has no ambiguous characters and can be read from WhatsApp',()=>{const code=randomCode();assert.match(code,/^MCS-[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{4}$/);assert.equal(extractCode('Hey MCS-7K2Q please'),'MCS-7K2Q');assert.equal(extractCode('nothing here'),null);});
test('public response is an allowlist and never leaks internal auction data',()=>{const vehicle={year:2020,make:'Honda',model:'Civic',vin:'SECRET',seller:'seller',location:'FL - Miami',mmrCents:1000000,conditionGrade:'4.2',startsAt:'2026-09-29T13:30:00Z',cleanTitle:true,odometerOk:true};const output=publicResponse({token:'x'.repeat(32),version:'V1',reference_code:'AB234',customer_name:'Ana',expires_at:'2099-01-01T00:00:00Z'},[{short_code:'MCS-7K2Q',vehicle_snapshot:publicVehicle(vehicle),photo_paths:[]}]);const serialized=JSON.stringify(output);for(const forbidden of ['SECRET','seller','conditionGrade','vin','Buy Now','lane','comment'])assert.doesNotMatch(serialized,new RegExp(forbidden,'i'));assert.equal(output.cars[0].vehicle.state,'Florida');});
test('public route, noindex rewrite, webhook isolation and auto-reply block are present',()=>{assert.match(read('vercel.json'),/"source": "\/v\/:token/);assert.match(read('v/index.html'),/noindex,nofollow/);assert.match(read('whatsapp-receiver.js'),/captureVitrineInterest/);assert.match(read('whatsapp-auto-reply.js'),/VITRINE_INTEREST/);assert.match(read('panel-push.js'),/sendVitrinePush/);});
test('customer copy has no em dash or final periods in required lines',()=>{const source=read('v/vitrine.js');for(const text of ['A reference, not a fixed price','The final price is set on auction day','Tap the car you like and send the message','Our team replies with photos and full details','This auction has ended','Ask us about similar cars'])assert.match(source,new RegExp(text));assert.doesNotMatch(source,/A reference, not a fixed price\.|This auction has ended\./);});
