'use strict';
const crypto=require('node:crypto');
const {isUuid,jsonBody,patchRows,requirePanel,rows,safeText,send,supabase}=require('../../panel-server');
const {detectedImage,readPrint,sha256}=require('../../panel-sms-print');
const BUCKET='mcs-panel-attachments';
const safeName=(v)=>String(v||'print').normalize('NFC').replace(/[^a-zA-Z0-9._-]/g,'_').replace(/^\.+/,'').slice(0,120)||'print';
const path=(v)=>String(v).split('/').map(encodeURIComponent).join('/');
async function data(ctx,id){return (await rows(ctx,'sms_print_reads',{select:'id,status,source_journey_id,source_contact_id,original_filename,mime_type,byte_size,quarantine_path,storage_path,extracted_json,error_code,confirmed_journey_id,confirmed_contact_id,message_id,attachment_id,created_phone_id,prior_primary_phone_id,created_contact,created_journey,undone_at,created_at',environment:'eq.'+ctx.environment,id:'eq.'+id,limit:'1'}))[0]||null;}
async function refTarget(ctx,value){const ref=String(value||'').trim().toUpperCase();if(!/^[A-HJ-NP-Z2-9]{5}$/.test(ref))return null;let found=await rows(ctx,'journeys',{select:'id,contact_id,reference_code',environment:'eq.'+ctx.environment,reference_code:'eq.'+ref,limit:'1'});if(found[0])return found[0];const links=await rows(ctx,'journey_refs',{select:'journey_id',environment:'eq.'+ctx.environment,ref_code:'eq.'+ref,limit:'1'});return links[0]?((await rows(ctx,'journeys',{select:'id,contact_id,reference_code',environment:'eq.'+ctx.environment,id:'eq.'+links[0].journey_id,limit:'1'}))[0]||null):null;}
async function move(ctx,record){const attachment=crypto.randomUUID(),canonical=`panel/${ctx.environment}/${attachment}/${record.original_filename}`;await supabase(ctx.config.url,ctx.config.secretKey,'/storage/v1/object/move',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({bucketId:BUCKET,sourceKey:record.quarantine_path,destinationKey:canonical})});return {attachment,canonical};}
async function read(ctx,record){
  if(!['UPLOADING','READY'].includes(record.status))throw Error(record.error_code||'SMS_PRINT_UNAVAILABLE');
  const claimed=await supabase(ctx.config.url,ctx.config.secretKey,'/rest/v1/sms_print_reads?environment=eq.'+ctx.environment+'&id=eq.'+record.id+'&status=eq.'+record.status,{method:'PATCH',headers:{'content-type':'application/json',prefer:'return=representation'},body:JSON.stringify({status:'READING',error_code:null})});
  if(!claimed[0])throw Error('SMS_PRINT_READING');
  try{const object=await fetch(ctx.config.url+'/storage/v1/object/'+BUCKET+'/'+path(record.quarantine_path),{headers:{apikey:ctx.config.secretKey,authorization:'Bearer '+ctx.config.secretKey}});if(!object.ok)throw Error('SMS_PRINT_UPLOAD_NOT_FOUND');const bytes=Buffer.from(await object.arrayBuffer()),mime=detectedImage(record.original_filename,record.mime_type,bytes.length,bytes.subarray(0,64));if(!mime)throw Error('SMS_PRINT_INVALID_IMAGE');const extracted=await readPrint(ctx,bytes,mime);await patchRows(ctx,'sms_print_reads',{environment:'eq.'+ctx.environment,id:'eq.'+record.id},{status:'READY',byte_size:bytes.length,sha256:sha256(bytes),extracted_json:extracted,error_code:null});const ready=await data(ctx,record.id);return {read:ready,refTarget:await refTarget(ctx,extracted.ref)};}
  catch(error){await patchRows(ctx,'sms_print_reads',{environment:'eq.'+ctx.environment,id:'eq.'+record.id},{status:'READY',extracted_json:{},error_code:String(error.message||'FAILED').slice(0,80)}).catch(()=>{});return {read:await data(ctx,record.id),manual:true,refTarget:null};}
}
module.exports=async(req,res)=>{const ctx=await requirePanel(req,res);if(!ctx)return;try{
  if(req.method==='GET'){const journey=String(req.query?.journeyId||'');if(!isUuid(journey))return send(res,400,{error:'SMS_PRINT_SOURCE_INVALID'});const confirmed=await rows(ctx,'sms_print_reads',{select:'id',environment:'eq.'+ctx.environment,confirmed_journey_id:'eq.'+journey,status:'eq.CONFIRMED',limit:'1'});return send(res,200,{confirmed:Boolean(confirmed[0])});}
  if(req.method!=='POST')return send(res,405,{error:'METHOD_NOT_ALLOWED'});const body=await jsonBody(req,48*1024);
  if(body.action==='sign'){const mime=detectedImage(body.filename,body.mimeType,Number(body.byteSize),body.magicBase64);if(!mime)return send(res,400,{error:'SMS_PRINT_INVALID_IMAGE'});const id=crypto.randomUUID(),filename=safeName(body.filename),journey=isUuid(body.journeyId)?body.journeyId:null,contact=isUuid(body.contactId)?body.contactId:null;if(journey){const owner=await rows(ctx,'journeys',{select:'contact_id',environment:'eq.'+ctx.environment,id:'eq.'+journey,limit:'1'});if(!owner[0]||(contact&&contact!==owner[0].contact_id))return send(res,400,{error:'SMS_PRINT_SOURCE_INVALID'});}const quarantine=`quarantine/${ctx.environment}/sms-print/${id}/${filename}`;await supabase(ctx.config.url,ctx.config.secretKey,'/rest/v1/sms_print_reads',{method:'POST',headers:{'content-type':'application/json',prefer:'return=minimal'},body:JSON.stringify({id,environment:ctx.environment,source_journey_id:journey,source_contact_id:contact,original_filename:filename,mime_type:mime,quarantine_path:quarantine,status:'UPLOADING',created_by:ctx.panel.id,updated_by:ctx.panel.id})});const signed=await supabase(ctx.config.url,ctx.config.secretKey,'/storage/v1/object/upload/sign/'+BUCKET+'/'+path(quarantine),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({})});return send(res,201,{readId:id,filename,quarantinePath:quarantine,uploadUrl:signed.url.startsWith('http')?signed.url:ctx.config.url+'/storage/v1'+signed.url,token:signed.token});}
  if(!isUuid(body.readId))return send(res,400,{error:'SMS_PRINT_ID_INVALID'});const record=await data(ctx,body.readId);if(!record)return send(res,404,{error:'SMS_PRINT_NOT_FOUND'});
  if(body.action==='read'||body.action==='retry'){if(body.action==='read'&&(record.status==='READY'||record.status==='CONFIRMED'))return send(res,200,{read:record,refTarget:await refTarget(ctx,record.extracted_json?.ref)});return send(res,200,await read(ctx,record));}
  if(body.action==='discard'){if(record.status==='CONFIRMED')return send(res,409,{error:'SMS_PRINT_CONFIRMED'});await patchRows(ctx,'sms_print_reads',{environment:'eq.'+ctx.environment,id:'eq.'+record.id},{status:'DISCARDED',updated_by:ctx.panel.id});return send(res,200,{discarded:true});}
  if(body.action==='undo'){const result=await supabase(ctx.config.url,ctx.config.secretKey,'/rest/v1/rpc/panel_sms_print_undo',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({p_environment:ctx.environment,p_actor:ctx.panel.id,p_read:record.id})});return send(res,200,result);}
  if(body.action==='photo'){if(record.status!=='READY'||!isUuid(body.targetJourneyId))return send(res,400,{error:'SMS_PRINT_TARGET_REQUIRED'});const stored=await move(ctx,record);const result=await supabase(ctx.config.url,ctx.config.secretKey,'/rest/v1/rpc/panel_sms_print_attach_photo',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({p_environment:ctx.environment,p_actor:ctx.panel.id,p_read:record.id,p_target_journey:body.targetJourneyId,p_attachment:stored.attachment,p_bucket:BUCKET,p_storage_path:stored.canonical})});return send(res,201,result);}
  if(body.action!=='confirm')return send(res,400,{error:'SMS_PRINT_ACTION_INVALID'});if(record.status==='CONFIRMED')return send(res,200,{journeyId:record.confirmed_journey_id,contactId:record.confirmed_contact_id,messageId:record.message_id,attachmentId:record.attachment_id,duplicate:true});if(record.status!=='READY')return send(res,409,{error:'SMS_PRINT_NOT_READY'});
  const values={phone:safeText(body.phone,40,true),name:safeText(body.name,160),ref:safeText(body.ref,8),message:safeText(body.message,25000,true),translation:safeText(body.translation,25000)};if(!values.phone||!values.message)return send(res,400,{error:'SMS_PRINT_VALUES_INVALID'});const target=isUuid(body.targetJourneyId)?body.targetJourneyId:null,readRefTarget=await refTarget(ctx,values.ref);if(record.source_journey_id&&readRefTarget&&readRefTarget.id!==record.source_journey_id&&!target&&body.keepSource!==true)return send(res,409,{error:'SMS_PRINT_REF_DECISION_REQUIRED',refTarget:readRefTarget});
  const targetBefore=target||record.source_journey_id||readRefTarget?.id||null;let contactBefore=null,beforePhones=[],priorPrimary=null;if(targetBefore){const owner=await rows(ctx,'journeys',{select:'contact_id',environment:'eq.'+ctx.environment,id:'eq.'+targetBefore,limit:'1'});contactBefore=owner[0]?.contact_id||null;}if(contactBefore){beforePhones=await rows(ctx,'contact_phones',{select:'id,is_primary',environment:'eq.'+ctx.environment,contact_id:'eq.'+contactBefore,is_current:'eq.true',retired_at:'is.null'});priorPrimary=beforePhones.find((phone)=>phone.is_primary)?.id||null;}
  const stored=await move(ctx,record);const result=await supabase(ctx.config.url,ctx.config.secretKey,'/rest/v1/rpc/panel_sms_print_confirm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({p_environment:ctx.environment,p_actor:ctx.panel.id,p_read:record.id,p_target_journey:target,p_keep_source:body.keepSource===true,p_phone:values.phone,p_name:values.name,p_ref:values.ref,p_message:values.message,p_translation:values.translation,p_attachment:stored.attachment,p_bucket:BUCKET,p_storage_path:stored.canonical})});const after=await rows(ctx,'contact_phones',{select:'id',environment:'eq.'+ctx.environment,contact_id:'eq.'+result.contactId,is_current:'eq.true',retired_at:'is.null'});const known=new Set(beforePhones.map((phone)=>phone.id));const createdPhone=after.find((phone)=>!known.has(phone.id))?.id||null;await patchRows(ctx,'sms_print_reads',{environment:'eq.'+ctx.environment,id:'eq.'+record.id},{created_phone_id:createdPhone,prior_primary_phone_id:priorPrimary,created_contact:!contactBefore,created_journey:!targetBefore});return send(res,201,result);
}catch(_){return send(res,500,{error:'SMS_PRINT_REQUEST_FAILED'});}};
