'use strict';
const crypto=require('node:crypto');
const {insert,isUuid,jsonBody,patchRows,requirePanel,rows,rpc,safeText,send,supabase}=require('../../panel-server');
const {ensureJourney,leadData,orders}=require('../../panel-lead');
const phoneLink=require('../../panel-phone-link');
const calcMessage=require('../../panel-calc-message');
const {detectedImage,readPrint,sameMessage,sha256}=require('../../panel-sms-print');
const BUCKET='mcs-panel-attachments';
const safeName=(v)=>String(v||'print').normalize('NFC').replace(/[^a-zA-Z0-9._-]/g,'_').replace(/^\.+/,'').slice(0,120)||'print';
const path=(v)=>String(v).split('/').map(encodeURIComponent).join('/');
async function data(ctx,id){return (await rows(ctx,'sms_print_reads',{select:'id,status,source_journey_id,source_contact_id,original_filename,mime_type,byte_size,quarantine_path,storage_path,sha256,extracted_json,error_code,confirmed_journey_id,confirmed_contact_id,message_id,attachment_id,created_phone_id,prior_primary_phone_id,created_contact,created_journey,undone_at,created_at,updated_at',environment:'eq.'+ctx.environment,id:'eq.'+id,limit:'1'}))[0]||null;}
async function refTarget(ctx,value){const ref=String(value||'').trim().toUpperCase();if(!/^[A-HJ-NP-Z2-9]{5}$/.test(ref))return null;let found=await rows(ctx,'journeys',{select:'id,contact_id,reference_code',environment:'eq.'+ctx.environment,reference_code:'eq.'+ref,limit:'1'});if(found[0])return found[0];const links=await rows(ctx,'journey_refs',{select:'journey_id',environment:'eq.'+ctx.environment,ref_code:'eq.'+ref,limit:'1'});return links[0]?((await rows(ctx,'journeys',{select:'id,contact_id,reference_code',environment:'eq.'+ctx.environment,id:'eq.'+links[0].journey_id,limit:'1'}))[0]||null):null;}
// The attachment row only exists after the confirm/photo RPC, which sets attachment_id itself (the column has a
// foreign key). Writing attachment_id here first broke every print confirmation; a retry after a moved file reuses
// the id that is already in its storage path.
const attachmentFromPath=(storagePath)=>{const id=String(storagePath||'').split('/')[2];return isUuid(id)?id:null;};
async function move(ctx,record){if(record.storage_path&&isUuid(record.attachment_id))return {attachment:record.attachment_id,canonical:record.storage_path};const attachment=isUuid(record.attachment_id)?record.attachment_id:attachmentFromPath(record.storage_path)||crypto.randomUUID(),canonical=record.storage_path||`panel/${ctx.environment}/${attachment}/${record.original_filename}`;if(!record.storage_path){try{await supabase(ctx.config.url,ctx.config.secretKey,'/storage/v1/object/move',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({bucketId:BUCKET,sourceKey:record.quarantine_path,destinationKey:canonical})});}catch(_){throw Error('SMS_PRINT_STORAGE_MOVE_FAILED');}}await patchRows(ctx,'sms_print_reads',{environment:'eq.'+ctx.environment,id:'eq.'+record.id},{storage_path:canonical,updated_by:ctx.panel.id});return {attachment,canonical};}
const normalizePhone=(value)=>{const digits=String(value||'').replace(/\D/g,'');return digits.length===10?'+1'+digits:digits.length===11&&digits[0]==='1'?`+${digits}`:String(value||'').startsWith('+')?String(value):null;};
async function newestJourney(ctx,contactId){return (await rows(ctx,'journeys',{select:'id,contact_id,reference_code',environment:'eq.'+ctx.environment,contact_id:'eq.'+contactId,order:'created_at.desc',limit:'1'}))[0]||null;}
// The fichas that own a phone (through the contact's current phone) and the written decision of panel-phone-link.
async function phoneDecision(ctx,phone,values){const owners=await rows(ctx,'contact_phones',{select:'contact_id',environment:'eq.'+ctx.environment,phone_e164:'eq.'+phone,is_current:'eq.true',retired_at:'is.null',limit:'20'});const contactIds=[...new Set(owners.map((row)=>row.contact_id).filter(isUuid))];if(!contactIds.length)return phoneLink.decide({fichas:[],values});const [journeys,contacts]=await Promise.all([rows(ctx,'journeys',{select:'id,contact_id,vehicle_text',environment:'eq.'+ctx.environment,contact_id:'in.('+contactIds.join(',')+')',limit:'50'}),rows(ctx,'contacts',{select:'id,display_name',environment:'eq.'+ctx.environment,id:'in.('+contactIds.join(',')+')',limit:'20'})]);const nameOf=new Map(contacts.map((row)=>[row.id,row.display_name]));return phoneLink.decide({fichas:journeys.map((row)=>({id:row.id,contactName:nameOf.get(row.contact_id)||'',vehicleText:row.vehicle_text||''})),values});}
async function automaticTarget(ctx,record,values,strict=false){const byRef=await refTarget(ctx,values.ref);if(byRef&&(!record.source_journey_id||byRef.id!==record.source_journey_id))return {target:byRef,matchedBy:'ref'};if(record.source_journey_id)return {target:{id:record.source_journey_id,contact_id:record.source_contact_id},matchedBy:'origem'};if(values.ref&&(await orders(ctx,String(values.ref).trim().toUpperCase()))[0])return {target:null,matchedBy:'ref-calculadora'};const phone=normalizePhone(values.phone);if(phone){const decision=await phoneDecision(ctx,phone,values);if(decision.action==='LINK'){const target=await rows(ctx,'journeys',{select:'id,contact_id,reference_code',environment:'eq.'+ctx.environment,id:'eq.'+decision.journeyId,limit:'1'});if(target[0])return {target:target[0],matchedBy:'telefone'};}if(decision.action==='QUEUE'||(decision.action==='QUARANTINE'&&strict))return {target:null,matchedBy:'telefone-fila',decision};}const name=String(values.name||'').trim();if(name){const contacts=await rows(ctx,'contacts',{select:'id',environment:'eq.'+ctx.environment,display_name:'eq.'+name,limit:'2'});if(contacts.length===1){const target=await newestJourney(ctx,contacts[0].id);if(target)return {target:null,matchedBy:'nome',candidate:target};}}return {target:null,matchedBy:'novo'};}
// A18: a name alone never attaches a print to someone. The print waits in ENTRADA for the operator.
const NAME_REVIEW='NAME_MATCH_REVIEW';
async function duplicateMessage(ctx,journeyId,text){if(!journeyId||!text)return false;const links=await rows(ctx,'message_journeys',{select:'message_id',environment:'eq.'+ctx.environment,journey_id:'eq.'+journeyId,undone_at:'is.null',limit:'500'});const ids=links.map((row)=>row.message_id).filter(isUuid);if(!ids.length)return false;const messages=await rows(ctx,'messages',{select:'id,body_text,body_normalized',environment:'eq.'+ctx.environment,id:'in.('+ids.join(',')+')',limit:'500'});const normalized=String(text).trim().toLowerCase().replace(/\s+/g,' ');return messages.some((message)=>message.body_normalized===normalized||sameMessage(message.body_text,text));}
// A print without a phone can still be saved when its Ref (or the chosen ficha) already identifies one contact
// with exactly one current phone: the proven identity is reused, never a phone guessed from the print.
async function inheritedPhone(ctx,journeyId){const journey=await rows(ctx,'journeys',{select:'contact_id',environment:'eq.'+ctx.environment,id:'eq.'+journeyId,limit:'1'});if(!journey[0])return null;const phones=await rows(ctx,'contact_phones',{select:'phone_e164',environment:'eq.'+ctx.environment,contact_id:'eq.'+journey[0].contact_id,is_current:'eq.true',retired_at:'is.null',limit:'2'});return phones.length===1?phones[0].phone_e164:null;}
async function duplicateResult(ctx,row,fallbackRef){const [journey]=row.confirmed_journey_id?await rows(ctx,'journeys',{select:'reference_code',environment:'eq.'+ctx.environment,id:'eq.'+row.confirmed_journey_id,limit:'1'}):[],[contact]=row.confirmed_contact_id?await rows(ctx,'contacts',{select:'display_name',environment:'eq.'+ctx.environment,id:'eq.'+row.confirmed_contact_id,limit:'1'}):[];return {journeyId:row.confirmed_journey_id,contactId:row.confirmed_contact_id,messageId:row.message_id,attachmentId:row.attachment_id,duplicate:true,name:contact?.display_name||null,ref:journey?.reference_code||fallbackRef||null};}
async function read(ctx,record){
  // M21: a read that died halfway (READING for more than 2 minutes) can be claimed again
  const staleReading=record.status==='READING'&&Date.now()-Date.parse(record.updated_at||record.created_at||0)>2*60*1000;
  if(!['UPLOADING','READY'].includes(record.status)&&!staleReading)throw Error(record.error_code||'SMS_PRINT_UNAVAILABLE');
  const claimed=await supabase(ctx.config.url,ctx.config.secretKey,'/rest/v1/sms_print_reads?environment=eq.'+ctx.environment+'&id=eq.'+record.id+'&status=eq.'+record.status+(staleReading?'&updated_at=eq.'+encodeURIComponent(record.updated_at):''),{method:'PATCH',headers:{'content-type':'application/json',prefer:'return=representation'},body:JSON.stringify({status:'READING',error_code:null,updated_at:new Date().toISOString()})});
  if(!claimed[0])throw Error('SMS_PRINT_READING');
  try{const object=await fetch(ctx.config.url+'/storage/v1/object/'+BUCKET+'/'+path(record.quarantine_path),{headers:{apikey:ctx.config.secretKey,authorization:'Bearer '+ctx.config.secretKey}});if(!object.ok)throw Error('SMS_PRINT_UPLOAD_NOT_FOUND');const bytes=Buffer.from(await object.arrayBuffer()),mime=detectedImage(record.original_filename,record.mime_type,bytes.length,bytes.subarray(0,64));if(!mime)throw Error('SMS_PRINT_INVALID_IMAGE');const extracted=await readPrint(ctx,bytes,mime);await patchRows(ctx,'sms_print_reads',{environment:'eq.'+ctx.environment,id:'eq.'+record.id},{status:'READY',byte_size:bytes.length,sha256:sha256(bytes),extracted_json:extracted,error_code:null});const ready=await data(ctx,record.id);return {read:ready,refTarget:await refTarget(ctx,extracted.ref)};}
  catch(error){await patchRows(ctx,'sms_print_reads',{environment:'eq.'+ctx.environment,id:'eq.'+record.id},{status:'READY',extracted_json:{},error_code:String(error.message||'FAILED').slice(0,80)}).catch(()=>{});return {read:await data(ctx,record.id),manual:true,refTarget:null};}
}
// The confirm branch as a function so the cron can run it too (reply(code,payload) instead of the response).
// The phone of the print already belongs to another contact: the panel offers "Guardar em [nome]" instead of a generic error.
async function phoneOwner(ctx,phone,contactBefore){
  const digits=String(phone||'').replace(/\D/g,'');const local=digits.length===10?'+1'+digits:digits.length>=11?'+'+digits:null;
  const normalized=await rpc(ctx,'panel_normalize_phone',{p_value:phone}).catch(()=>null)||local;if(!normalized)return null;
  const holders=await rows(ctx,'contact_phones',{select:'contact_id',environment:'eq.'+ctx.environment,phone_e164:'eq.'+normalized,is_current:'eq.true',retired_at:'is.null',limit:'5'});
  const owner=holders.map((row)=>row.contact_id).find((id)=>id&&id!==contactBefore);if(!owner)return null;
  const [contact]=await rows(ctx,'contacts',{select:'display_name',environment:'eq.'+ctx.environment,id:'eq.'+owner,limit:'1'});
  const journeys=await rows(ctx,'journeys',{select:'id,reference_code,status',environment:'eq.'+ctx.environment,contact_id:'eq.'+owner,order:'updated_at.desc',limit:'5'});
  const journey=journeys.find((row)=>row.status!=='ENCERRADO')||journeys[0];if(!journey)return null;
  return {contactId:owner,journeyId:journey.id,name:contact?.display_name||normalized,ref:journey.reference_code||null};
}
// The Ref of the print goes to the ficha that received it, even when the ficha already has an internal code
// (the confirm only fills an empty code). Never a Ref that belongs to another ficha.
async function linkPrintRef(ctx,journeyId,value){
  const ref=String(value||'').trim().toUpperCase();if(!/^[A-HJ-NP-Z2-9]{5}$/.test(ref)||!isUuid(journeyId))return;
  const owner=await refTarget(ctx,ref);if(owner&&owner.id!==journeyId)return;
  const linked=await rows(ctx,'journey_refs',{select:'journey_id',environment:'eq.'+ctx.environment,journey_id:'eq.'+journeyId,ref_code:'eq.'+ref,limit:'1'});if(linked[0])return;
  await insert(ctx,'journey_refs',{environment:ctx.environment,journey_id:journeyId,ref_code:ref,created_at:new Date().toISOString(),created_by:ctx.panel.id},false).catch(()=>{});
}
async function confirmPrint(ctx,record,body,reply){
if(record.status==='CONFIRMED')return reply(200,await duplicateResult(ctx,record,record.extracted_json?.ref));if(record.status!=='READY')return reply(409,{error:'SMS_PRINT_NOT_READY'});
  const values={phone:safeText(body.phone,40,true),name:safeText(body.name,160),ref:safeText(body.ref,8),message:safeText(body.message,25000),translation:safeText(body.translation,25000)},automatic=body.auto===true,resolved=automatic?(body.newLead===true?{target:null,matchedBy:'novo'}:await automaticTarget(ctx,record,values,body.strict===true)):{target:isUuid(body.targetJourneyId)?{id:body.targetJourneyId}:null,matchedBy:'manual'};let target=resolved.target?.id||null;const readRefTarget=await refTarget(ctx,values.ref);if(record.sha256){const duplicate=await rows(ctx,'sms_print_reads',{select:'confirmed_journey_id,confirmed_contact_id,message_id,attachment_id',environment:'eq.'+ctx.environment,sha256:'eq.'+record.sha256,status:'eq.CONFIRMED',limit:'1'});if(duplicate[0]){await patchRows(ctx,'sms_print_reads',{environment:'eq.'+ctx.environment,id:'eq.'+record.id},{status:'DISCARDED',error_code:'DUPLICATE_CONFIRMED',updated_by:ctx.panel.id});return reply(200,await duplicateResult(ctx,duplicate[0],values.ref));}}if(resolved.decision){await patchRows(ctx,'sms_print_reads',{environment:'eq.'+ctx.environment,id:'eq.'+record.id},{pending_reason:phoneLink.encode(resolved.decision),updated_by:ctx.panel.id});return reply(202,{review:true,queue:resolved.decision.reason,text:resolved.decision.text,candidates:resolved.decision.candidates,readId:record.id});}if(resolved.candidate){await patchRows(ctx,'sms_print_reads',{environment:'eq.'+ctx.environment,id:'eq.'+record.id},{error_code:NAME_REVIEW,updated_by:ctx.panel.id});return reply(202,{review:true,readId:record.id,candidateJourneyId:resolved.candidate.id});}if(!values.message&&!target&&resolved.matchedBy==='ref-calculadora'){target=(await ensureJourney(ctx,await leadData(ctx,values.ref))).id;}if(target&&await duplicateMessage(ctx,target,values.message)){const stored=await move(ctx,record),photo=await supabase(ctx.config.url,ctx.config.secretKey,'/rest/v1/rpc/panel_sms_print_attach_photo',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({p_environment:ctx.environment,p_actor:ctx.panel.id,p_read:record.id,p_target_journey:target,p_attachment:stored.attachment,p_bucket:BUCKET,p_storage_path:stored.canonical})});return reply(201,{...photo,photoOnly:true,duplicateMessage:true});}if(!values.message){if(!target)return reply(400,{error:'SMS_PRINT_PHOTO_TARGET_REQUIRED'});const stored=await move(ctx,record),photo=await supabase(ctx.config.url,ctx.config.secretKey,'/rest/v1/rpc/panel_sms_print_attach_photo',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({p_environment:ctx.environment,p_actor:ctx.panel.id,p_read:record.id,p_target_journey:target,p_attachment:stored.attachment,p_bucket:BUCKET,p_storage_path:stored.canonical})});return reply(201,{...photo,photoOnly:true});}// (e) The reader puts the Ref of the print in its own field and may leave the calculator's last line out of the text: the text
  // is kept complete, with the "Ref: XXXXX" line the print showed (only a code read from the print, never a guessed one).
  if(/^[A-HJ-NP-Z2-9]{5}$/i.test(values.ref||'')&&calcMessage.isCalculator(values.message)&&calcMessage.parse(values.message).refState==='SEM_LINHA_REF')values.message=values.message.replace(/\s+$/,'')+'\nRef: '+values.ref.toUpperCase();
  let inherited=false;if(!values.phone&&target){const known=await inheritedPhone(ctx,target);if(known){values.phone=known;inherited=true;}}if(!values.phone)return reply(400,{error:'SMS_PRINT_VALUES_INVALID'});if(!automatic&&record.source_journey_id&&readRefTarget&&readRefTarget.id!==record.source_journey_id&&!target&&body.keepSource!==true)return reply(409,{error:'SMS_PRINT_REF_DECISION_REQUIRED',refTarget:readRefTarget});
  const targetBefore=target||record.source_journey_id||readRefTarget?.id||null;let contactBefore=null,beforePhones=[],priorPrimary=null;if(targetBefore){const owner=await rows(ctx,'journeys',{select:'contact_id',environment:'eq.'+ctx.environment,id:'eq.'+targetBefore,limit:'1'});contactBefore=owner[0]?.contact_id||null;}if(contactBefore){beforePhones=await rows(ctx,'contact_phones',{select:'id,is_primary',environment:'eq.'+ctx.environment,contact_id:'eq.'+contactBefore,is_current:'eq.true',retired_at:'is.null'});priorPrimary=beforePhones.find((phone)=>phone.is_primary)?.id||null;}
  const owner=await phoneOwner(ctx,values.phone,contactBefore);if(owner)return reply(409,{error:'SMS_PRINT_PHONE_OWNER',reason:owner});
  const stored=await move(ctx,record);const result=await supabase(ctx.config.url,ctx.config.secretKey,'/rest/v1/rpc/panel_sms_print_confirm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({p_environment:ctx.environment,p_actor:ctx.panel.id,p_read:record.id,p_target_journey:target,p_keep_source:automatic||body.keepSource===true,p_phone:values.phone,p_name:values.name,p_ref:values.ref,p_message:values.message,p_translation:values.translation,p_attachment:stored.attachment,p_bucket:BUCKET,p_storage_path:stored.canonical})});const after=await rows(ctx,'contact_phones',{select:'id',environment:'eq.'+ctx.environment,contact_id:'eq.'+result.contactId,is_current:'eq.true',retired_at:'is.null'});const known=new Set(beforePhones.map((phone)=>phone.id));const createdPhone=after.find((phone)=>!known.has(phone.id))?.id||null;await patchRows(ctx,'sms_print_reads',{environment:'eq.'+ctx.environment,id:'eq.'+record.id},{created_phone_id:createdPhone,prior_primary_phone_id:priorPrimary,created_contact:!contactBefore,created_journey:!targetBefore});await linkPrintRef(ctx,result.journeyId,values.ref);const contact=await rows(ctx,'contacts',{select:'display_name',environment:'eq.'+ctx.environment,id:'eq.'+result.contactId,limit:'1'});const journey=await rows(ctx,'journeys',{select:'reference_code',environment:'eq.'+ctx.environment,id:'eq.'+result.journeyId,limit:'1'});return reply(201,{...result,name:contact[0]?.display_name||null,ref:journey[0]?.reference_code||values.ref||null,matchedBy:resolved.matchedBy,inheritedPhone:inherited});
}

module.exports=async(req,res)=>{const ctx=await requirePanel(req,res);if(!ctx)return;try{
  if(req.method==='GET')return send(res,410,{error:'SMS_PRINT_STATUS_INCLUDED_IN_LISTS'});
  if(req.method!=='POST')return send(res,405,{error:'METHOD_NOT_ALLOWED'});const body=await jsonBody(req,48*1024);
  if(body.action==='sign'){if(Number(body.byteSize)>5*1024*1024)return send(res,400,{error:'SMS_PRINT_TOO_LARGE'});if(/\.hei[cf]$/i.test(String(body.filename||''))||/hei[cf]/i.test(String(body.mimeType||'')))return send(res,400,{error:'SMS_PRINT_HEIC'});const mime=detectedImage(body.filename,body.mimeType,Number(body.byteSize),body.magicBase64);if(!mime)return send(res,400,{error:'SMS_PRINT_INVALID_IMAGE'});const id=crypto.randomUUID(),filename=safeName(body.filename),journey=isUuid(body.journeyId)?body.journeyId:null,contact=isUuid(body.contactId)?body.contactId:null;if(journey){const owner=await rows(ctx,'journeys',{select:'contact_id',environment:'eq.'+ctx.environment,id:'eq.'+journey,limit:'1'});if(!owner[0]||(contact&&contact!==owner[0].contact_id))return send(res,400,{error:'SMS_PRINT_SOURCE_INVALID'});}const quarantine=`quarantine/${ctx.environment}/sms-print/${id}/${filename}`;await supabase(ctx.config.url,ctx.config.secretKey,'/rest/v1/sms_print_reads',{method:'POST',headers:{'content-type':'application/json',prefer:'return=minimal'},body:JSON.stringify({id,environment:ctx.environment,source_journey_id:journey,source_contact_id:contact,original_filename:filename,mime_type:mime,quarantine_path:quarantine,status:'UPLOADING',created_by:ctx.panel.id,updated_by:ctx.panel.id})});const signed=await supabase(ctx.config.url,ctx.config.secretKey,'/storage/v1/object/upload/sign/'+BUCKET+'/'+path(quarantine),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({})});return send(res,201,{readId:id,filename,quarantinePath:quarantine,uploadUrl:signed.url.startsWith('http')?signed.url:ctx.config.url+'/storage/v1'+signed.url,token:signed.token});}
  if(!isUuid(body.readId))return send(res,400,{error:'SMS_PRINT_ID_INVALID'});const record=await data(ctx,body.readId);if(!record)return send(res,404,{error:'SMS_PRINT_NOT_FOUND'});
  if(body.action==='read'||body.action==='retry'){if(body.action==='read'&&(record.status==='READY'||record.status==='CONFIRMED'))return send(res,200,{read:record,refTarget:await refTarget(ctx,record.extracted_json?.ref)});return send(res,200,await read(ctx,record));}
  if(body.action==='discard'){if(record.status==='CONFIRMED')return send(res,409,{error:'SMS_PRINT_CONFIRMED'});await patchRows(ctx,'sms_print_reads',{environment:'eq.'+ctx.environment,id:'eq.'+record.id},{status:'DISCARDED',updated_by:ctx.panel.id});return send(res,200,{discarded:true});}
  if(body.action==='undo'){const result=await supabase(ctx.config.url,ctx.config.secretKey,'/rest/v1/rpc/panel_sms_print_undo',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({p_environment:ctx.environment,p_actor:ctx.panel.id,p_read:record.id})});return send(res,200,result);}
  if(body.action==='photo'){if(record.status!=='READY'||!isUuid(body.targetJourneyId))return send(res,400,{error:'SMS_PRINT_TARGET_REQUIRED'});const stored=await move(ctx,record);const result=await supabase(ctx.config.url,ctx.config.secretKey,'/rest/v1/rpc/panel_sms_print_attach_photo',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({p_environment:ctx.environment,p_actor:ctx.panel.id,p_read:record.id,p_target_journey:body.targetJourneyId,p_attachment:stored.attachment,p_bucket:BUCKET,p_storage_path:stored.canonical})});return send(res,201,result);}
  { const outcome=await confirmPrint(ctx,record,body,(code,payload)=>({code,payload}));return send(res,outcome.code,outcome.payload); }
}catch(error){return send(res,500,{error:error?.message==='SMS_PRINT_STORAGE_MOVE_FAILED'?'SMS_PRINT_STORAGE_MOVE_FAILED':'SMS_PRINT_REQUEST_FAILED'});}};

module.exports.confirmPrint=confirmPrint;
module.exports.readPrintRecord=read;
module.exports.printRecord=data;
